from functions import *

# print(P_m)
# print(W_om)
# print(find_k_L())
# print('ln(l_pr) = ' + str(math.log(l_pr)))
# print('Q_om = ' + str(Q_om))
# print('g_mp = ' + str(g_mp))
# print('miu_1 = ' + str(find_miu1()))
# print('miu_g = ' + str(find_miu_g()))
# print('k_g = ' + str(find_k_g()))

print(g_mp)
print('G_mp = ' + str(G_mp))
print(W_om)
print('P_m = ' + str(P_m))
print(Q_om)
print('Q_m = ' + str(Q_m))
print('P_l = ' + str(cables[cable]['P_l']))
print('S = ' + str(cables[cable]['S']))
print('gamma1 = ' + str(gamma_1))
print('gamma2 = ' + str(gamma_2))
print('gamma3 = ' + str(gamma_3))
print('gamma4 = ' + str(gamma_4))
print('gamma5 = ' + str(gamma_5))
print('gamma6 = ' + str(gamma_6))
print('gamma7 = ' + str(gamma_7))
print('betta = ' + str(betta))
# print('l-1k = ' + str(l_1k))
# print('sigma_sr = ' + str(sigma_sr), 'betta = ' + str(betta), 'alfa_temp = ' + str(alfa_temp),
#       'sigma_nb = ' + str(sigma_nb))
print('find_l_1k = ' + str(find_l_1k()))
print('find_l_2k = ' + str(find_l_2k()))
print('find_l_3k = ' + str(find_l_3k()))
print('f_gab = ' + str(f_gab))
print('gamma_ozh_nb = ' + str(gamma_ozh_nb))
print('l_gab_ozh = ' + str(l_gab_ozh))
