from functions import *

# print(P_m)
# print(W_om)
# print(find_k_L())
# print('ln(l_pr) = ' + str(math.log(l_pr)))
# print('Q_om = ' + str(Q_om))
# print('g_mp = ' + str(g_mp))
# print('miu_1 = ' + str(find_miu1()))
# print('miu_g = ' + str(find_miu_g()))
# print('k_g = ' + str(find_k_g()))

print(g_mp)
print('G_mp = ' + str(find_G_mp()))
print(W_om)
print('P_m(0) = ' + str(find_P_m()))
print(Q_om)
print('Q_m(0) = ' + str(find_Q_m()))
print('P_l = ' + str(cables[cable]['P_l']))
print('S = ' + str(cables[cable]['S']))
print('gamma1    = ' + str(find_gamma_1()))
print('gamma2    = ' + str(find_gamma_2()))
print('gamma3    = ' + str(find_gamma_3()))
print('gamma4(0) = ' + str(find_gamma_4()))
print('gamma5(0) = ' + str(find_gamma_5()))
print('gamma6(0) = ' + str(find_gamma_6()))
print('gamma7(0) = ' + str(find_gamma_7()))
print('betta = ' + str(betta))
# print('l-1k = ' + str(l_1k))
# print('sigma_sr = ' + str(sigma_sr), 'betta = ' + str(betta), 'alfa_temp = ' + str(alfa_temp),
#       'sigma_nb = ' + str(sigma_nb))
print('find_l_1k = ' + str(find_l_1k()))
print('find_l_2k = ' + str(find_l_2k()))
print('find_l_3k = ' + str(find_l_3k()))
print('f_gab = ' + str(f_gab))
print('gamma_ozh_nb(0) = ' + str(find_gamma_ozh_nb(0)))
print('l_gab_ozh = ' + str(l_gab_ozh))


print('k_L simple = %s, k_L 240m = %s' % (find_k_L(), find_k_L(240)))
print('gamma4(240) = ' + str(find_gamma_4(240)))
print('gamma5(240) = ' + str(find_gamma_5(240)))
print('gamma6(240) = ' + str(find_gamma_6(240)))
print('gamma7(240) = ' + str(find_gamma_7(240)))
print('\n')
print('find_C_h(h) = ' + str(find_C_h(h)))
print('find_C_h(15) = ' + str(find_C_h(40)))
# print('find_C_h(h) = ' + str(find_C_h(h, C_h_dict[3])))
# print('find_C_h(15) = ' + str(find_C_h(15, C_h_dict[3])))
print('find_k1(h) = ' + str(find_k1(h)))
print('find_k1(15) = ' + str(find_k1(30)))
print('find_miu1() = ' + str(find_miu1(in_g_mp=9)))
print('find_miu1(15) = ' + str(find_miu1(20, 9)))
print('find_find_k_g(h) = ' + str(find_k_g(7.5)))
